In [1]:
import glob
import pandas as pd
import sqlite3

In [2]:
for num in range(1983,2019):
    df = pd.read_csv("sumoDemo/data/" +str(num)+".csv")
    df = df.append(df)

In [3]:
new = df[['rank']].copy()

In [5]:
new

       rank
0       Y1e
1       Y1w
2       Y2e
3       O1e
4       O1w
5       S1e
6       S1w
7       K1e
8       K1w
9       M1e
10      M1w
11      M2e
12      M2w
13      M3e
14      M3w
15      M4e
16      M4w
17      M5e
18      M5w
19      M6e
20      M6w
21      M7e
22      M7w
23      M8e
24      M8w
25      M9e
26      M9w
27     M10e
28     M10w
29     M11e
...     ...
3973  Jk15e
3974  Jk15w
3975  Jk16e
3976  Jk16w
3977  Jk17e
3978  Jk17w
3979  Jk18e
3980  Jk18w
3981  Jk19e
3982  Jk19w
3983  Jk20e
3984  Jk20w
3985  Jk21e
3986  Jk21w
3987  Jk22e
3988  Jk22w
3989  Jk23e
3990  Jk23w
3991  Jk24e
3992  Jk24w
3993  Jk25e
3994  Jk25w
3995  Jk26e
3996  Jk26w
3997  Jk27e
3998  Jk27w
3999  Jk28e
4000  Jk28w
4001  Jk29e
4002  Jk29w

[8006 rows x 1 columns]

In [16]:
new['rank'] = new['rank'].str.replace('\d+', '')

In [20]:
new['rank'] = new['rank'].str.replace('e', '')
new['rank'] = new['rank'].str.replace('w', '')

In [22]:
new=new.drop_duplicates()

In [23]:
new

      rank
0        Y
3        O
5        S
7        K
9        M
42       J
70      Ms
190     Sd
390     Jd
600     Jk
1040  SdTD

In [25]:
import requests
from bs4 import BeautifulSoup as bs

In [26]:
url="https://en.m.wikipedia.org/wiki/Template:Sumo_rank"
response = requests.get(url)

In [28]:
soup=bs(response.text,'html.parser')

In [36]:
things=soup.find_all('li')

In [42]:
things

[<li class="mw-ui-icon mw-ui-icon-element mw-ui-icon-minerva-edit" id="ca-edit" title="Edit the lead section of this page"><a class="edit-page" href="/w/index.php?title=Template:Sumo_rank&amp;action=edit&amp;section=0">Edit</a></li>,
 <li class="mw-ui-icon mw-ui-icon-element mw-ui-icon-minerva-watch watch-this-article" id="ca-watch"><a accesskey="w" href="/w/index.php?title=Special:UserLogin&amp;returnto=Template%3ASumo+rank" title="Add this page to your watchlist [w]"></a></li>,
 <li class="mw-ui-icon mw-ui-icon-element mw-ui-icon-minerva-language-switcher language-selector" title="Read in another language"><a href="/wiki/Special:MobileLanguages/Template:Sumo_rank">Read in another language</a></li>,
 <li><b>Y</b>: Yokozuna</li>,
 <li><b>O</b>: \u014czeki</li>,
 <li><b>S</b>: Sekiwake</li>,
 <li><b>K</b>: Komosubi</li>,
 <li><b>M</b>: Maegashira</li>,
 <li><b>J</b>: J\u016bry\u014d</li>,
 <li><b>MA</b>: Makushita</li>,
 <li><b>MT</b>: Makushita tsukedashi</li>,
 <li><b>SA</b>: Sandanme</li>,
 <li><b>ST</b>: Sandanme tsukedashi</li>,
 <li><b>JO</b>: Jonidan</li>,
 <li><b>JK</b>: Jonokuchi</li>,
 <li><b>BG</b>: Banzuke-gai</li>,
 <li><b>SD</b>: Shin-deshi</li>,
 <li><b>SJ</b>: Shinjo</li>,
 <li id="footer-places-terms-use"><a href="//m.wikimediafoundation.org/wiki/Terms_of_Use">Terms of Use</a></li>,
 <li id="footer-places-privacy"><a class="extiw" href="https://foundation.wikimedia.org/wiki/Privacy_policy" title="wmf:Privacy policy">Privacy</a></li>,
 <li id="footer-places-desktop-toggle"><a href="//en.wikipedia.org/w/index.php?title=Template:Sumo_rank&amp;mobileaction=toggle_view_desktop" id="mw-mf-display-toggle">Desktop</a></li>]

In [43]:
from lxml import html

In [44]:
tree = html.fromstring(page.content)

NameError: name 'page' is not defined